version: '3.8'
services:
  dev_dotnet_docker:
    image: mcr.microsoft.com/devcontainers/dotnet:10.0-noble
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    secrets:
        - SAMPLE_SECRET

secrets:
  SAMPLE_SECRET:
    file: ${HOME}/.docker-secrets/sample_secret.txt